services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3308:3306"  # Mapeamento da porta externa 3307 para a porta interna 3307
    volumes:
      - db_data:/var/lib/mysql

  node:
    build: ./node-app
    container_name: node-app
    restart: always
    depends_on:
      - db
    volumes:
      - "E:/Guilherme/FullCycle/Nginx_com_Node/node-app:/app"
      - /app/node_modules  # Volume separado para node_modules
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nodedb

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

volumes:
  db_data:
